"""Offline oracle-gain label generation utilities."""

from .audit import (
    flatten_metric_gains,
    spearman_rank_correlation,
    spearman_rank_correlations,
    summarize_metric_gains,
    summarize_oracle_audit,
    summarize_sanity_checks,
)
from .cache import (
    CACHE_SCHEMA_VERSION,
    build_reconstruction_cache_identity,
    build_reconstruction_cache_payload,
    file_identity,
    hash_cache_payload,
)
from .camera_alignment import (
    CameraAnchorAlignment,
    camera_anchor_condition_number,
    camera_centers_from_camera_to_world,
    camera_centers_from_world_to_camera,
    decode_vggt_pose_enc,
    estimate_camera_anchor_alignment,
    infer_image_size_hw,
    load_gt_camera_centers_by_view_id,
    load_pose_enc,
    load_reconstruction_camera_centers,
    predicted_camera_centers_from_pose_enc,
)
from .calibration import (
    AlignmentMetricResult,
    evaluate_alignment_and_metrics,
    flatten_gains,
    flatten_metrics,
    identical_cloud_gain_check,
    summarize_metric_stability,
)
from .dataset import OracleGainRecord, append_jsonl, build_memory_id, scene_split, write_jsonl
from .io import load_point_cloud, load_pose_matrix, view_id_from_path
from .metrics import (
    AlignmentDiagnostics,
    AlignmentResult,
    PointCloudMetrics,
    SimilarityTransform,
    align_sim3_icp,
    align_sim3_icp_with_diagnostics,
    apply_similarity_transform,
    compose_similarity_transforms,
    compute_metric_gains,
    compute_pointcloud_metrics,
    estimate_similarity_transform,
    voxel_downsample_points,
)

__all__ = [
    "AlignmentDiagnostics",
    "AlignmentMetricResult",
    "AlignmentResult",
    "CACHE_SCHEMA_VERSION",
    "CameraAnchorAlignment",
    "camera_anchor_condition_number",
    "camera_centers_from_camera_to_world",
    "camera_centers_from_world_to_camera",
    "decode_vggt_pose_enc",
    "estimate_camera_anchor_alignment",
    "infer_image_size_hw",
    "load_gt_camera_centers_by_view_id",
    "load_pose_enc",
    "load_reconstruction_camera_centers",
    "predicted_camera_centers_from_pose_enc",
    "OracleGainRecord",
    "PointCloudMetrics",
    "SimilarityTransform",
    "align_sim3_icp",
    "align_sim3_icp_with_diagnostics",
    "append_jsonl",
    "apply_similarity_transform",
    "build_memory_id",
    "build_reconstruction_cache_identity",
    "build_reconstruction_cache_payload",
    "compose_similarity_transforms",
    "compute_metric_gains",
    "compute_pointcloud_metrics",
    "estimate_similarity_transform",
    "evaluate_alignment_and_metrics",
    "file_identity",
    "flatten_gains",
    "flatten_metric_gains",
    "flatten_metrics",
    "hash_cache_payload",
    "identical_cloud_gain_check",
    "load_point_cloud",
    "load_pose_matrix",
    "scene_split",
    "spearman_rank_correlation",
    "spearman_rank_correlations",
    "summarize_metric_gains",
    "summarize_metric_stability",
    "summarize_oracle_audit",
    "summarize_sanity_checks",
    "view_id_from_path",
    "voxel_downsample_points",
    "write_jsonl",
]
